#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
NAME_FILE="NAME"
NAME_FILE_PATH="$DOKKU_ROOT/$APP/$NAME_FILE"

output=""
if [[ -f "$NAME_FILE_PATH" ]]; then
  COUNT=`cat $NAME_FILE_PATH | wc -w`
  if [[ "$COUNT" -ne "1" ]]; then
    echo "######> NAME file does not contain exactly one word" >&2
  else
    while read line
    do
      output="$output -name $line"
    done < $NAME_FILE_PATH
  fi
fi
echo "$STDIN$output"
