#!/usr/bin/env bash
# dokku-name 1.0.0

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
NAME_FILE="NAME"
NAME_FILE_PATH="$DOKKU_ROOT/$APP/$NAME_FILE"

function rename() {
  curr=$(sudo docker ps | grep $1 | awk '{print $12}')
  echo "curr is ${curr}"
  if [ -n $curr ]; then
    sudo docker rename $curr "$curr-old"
  fi
}

output=""
if [[ -f "$NAME_FILE_PATH" ]]; then
  # issue a cleanup, removes old named docker containers
  dokku cleanup
  # need to wait, docker doesn't appear to do this immediately
  sleep 2
  COUNT=`cat $NAME_FILE_PATH | wc -w`
  if [[ "$COUNT" -ne "1" ]]; then
    echo "######> NAME file does not contain exactly one word" >&2
  else
    while read line
    do
      rename $line
      output="$output --name=$line"
    done < $NAME_FILE_PATH
  fi
fi
echo "$STDIN$output"
